#pragma once

#define MAIN_Version "25d6c86"
#define KNX_Version "2.4.0+8e4c5bc"
#define MODULE_FunctionBlocks_Version "0.10.0+99e76b7"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_Common_Version "1.9.1+b30ecd2"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 9
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 25
#define MODULE_LogicModule_Version "4.4.1+cd1b5cc"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 4
#define MODULE_LogicModule_Version_Revision 1
#define MODULE_LogicModule_ETS 68
#define MODULE_IO_Version "0.1.0"
#define MODULE_IO_Version_Major 0
#define MODULE_IO_Version_Minor 1
#define MODULE_IO_Version_Revision 0
#define MODULE_IO_ETS 1
#define MODULE_HardwareConfig_Version "1.0.0+51dc43e"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Network_Version "0.8.1+4f3c9b5"
#define MODULE_Network_Version_Major 0
#define MODULE_Network_Version_Minor 8
#define MODULE_Network_Version_Revision 1
#define MODULE_Network_ETS 8
#define MODULE_UsbExchange_Version "0.0.2+55119fc"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 2
#define MODULE_UsbExchange_ETS 0
