#pragma once

#define MAIN_Version "87dc959"
#define KNX_Version "2.3.1+49c1072"
#define MODULE_FunctionBlocks_Version "0.10.0+e8ec058"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_Common_Version "1.8.1+6fdb851"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 8
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 24
#define MODULE_LogicModule_Version "4.3.0+45e2159"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 3
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 67
#define MODULE_IO_Version "0.1.0"
#define MODULE_IO_Version_Major 0
#define MODULE_IO_Version_Minor 1
#define MODULE_IO_Version_Revision 0
#define MODULE_IO_ETS 1
#define MODULE_HardwareConfig_Version "1.0.0+8bf530a"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Network_Version "0.6.0+b530c40"
#define MODULE_Network_Version_Major 0
#define MODULE_Network_Version_Minor 6
#define MODULE_Network_Version_Revision 0
#define MODULE_Network_ETS 6
#define MODULE_UsbExchange_Version "0.0.2+55119fc"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 2
#define MODULE_UsbExchange_ETS 0
#define MODULE_ConfigTransfer_Version "0.6.0-DEV+6ee3377"
#define MODULE_ConfigTransfer_Version_Major 0
#define MODULE_ConfigTransfer_Version_Minor 6
#define MODULE_ConfigTransfer_Version_Revision 0
#define MODULE_FileTransferModule_Version "0.1.5+629ca09"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define BUILD_DATETIME "2026-07-03 08:09:57"
#define BUILD_TIMESTAMP 1783058997
