#pragma once

#define MAIN_Version "False"
#define KNX_Version "2.3.1+49c1072"
#define MODULE_FunctionBlocks_Version "0.10.0+e8ec058"
#define MODULE_FunctionBlocks_Version_Major 0
#define MODULE_FunctionBlocks_Version_Minor 10
#define MODULE_FunctionBlocks_Version_Revision 0
#define MODULE_FunctionBlocks_ETS 10
#define MODULE_Common_Version "1.7.2+ec66671"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 7
#define MODULE_Common_Version_Revision 2
#define MODULE_Common_ETS 23
#define MODULE_LogicModule_Version "4.2.0+3188092"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 2
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 66
#define MODULE_IO_Version "0.1.0"
#define MODULE_IO_Version_Major 0
#define MODULE_IO_Version_Minor 1
#define MODULE_IO_Version_Revision 0
#define MODULE_IO_ETS 1
#define MODULE_HardwareConfig_Version "1.0.0+50ee2fc"
#define MODULE_HardwareConfig_Version_Major 1
#define MODULE_HardwareConfig_Version_Minor 0
#define MODULE_HardwareConfig_Version_Revision 0
#define MODULE_HardwareConfig_ETS 16
#define MODULE_Network_Version "0.5.4+6f8b448"
#define MODULE_Network_Version_Major 0
#define MODULE_Network_Version_Minor 5
#define MODULE_Network_Version_Revision 4
#define MODULE_Network_ETS 5
#define MODULE_UsbExchange_Version "0.0.2+55119fc"
#define MODULE_UsbExchange_Version_Major 0
#define MODULE_UsbExchange_Version_Minor 0
#define MODULE_UsbExchange_Version_Revision 2
#define MODULE_UsbExchange_ETS 0
